### ISSUE TITLE
can SDWebImage convert image to BPG?

### ISSUE THREAD

**Issue by bizibizi** [SDWebImage/SDWebImageBPGCoder#1]

**Comment by dreampiggy** [comment]
Currently NO. The reason is because the BPG codec we used [libbpg](https://bellard.org/bpg/), does not provide a function about BPG encoding. It contains only decoding functions.

But actually, there is BPG encoding tool in BPG project, it's a command line `bpgenc`. However, you know, iOS sandbox app does not allows to exec another process and to use that like macOS. So this is the fact...

**Comment by dreampiggy** [comment]
But I can not say it's impossible. At least it's not hard to implements on macOS by embed the `bpgenc` command line tool and feed it with images bitmap. For iOS, let me investigate later to find out the way.

**Comment by dreampiggy** [comment]
@bizibizi The BPG encoding feature is implements via #3 ! The BPG encoding, supports static BPG as well as animated BPG.

I use a modified version of original command line `bpgenc`, make it works as a library instead of sub-process program.

It's available with v0.4.0 version. You can upgrade and have a try.

**Comment by dreampiggy** [comment]
@bizibizi v0.4.0 is released. You can upgrade your dependency via Podfile.

**Comment by bizibizi** [comment]
@dreampiggy sounds great, thank you for your message!
